namespace Beacon.API.Models;

/// <summary>
/// Admin create payload for <c>education_records</c>. <see cref="EducationRecord.EducationRecordId"/> is generated by the database.
/// </summary>
public sealed class CreateEducationRecordRequest
{
    public int ResidentId { get; set; }

    public DateOnly RecordDate { get; set; }

    public string SchoolName { get; set; } = "";

    /// <summary>Enrolled or Not Enrolled</summary>
    public string EnrollmentStatus { get; set; } = "";

    public decimal? AttendanceRate { get; set; }

    public decimal? ProgressPercent { get; set; }

    /// <summary>NotStarted or InProgress</summary>
    public string CompletionStatus { get; set; } = "";

    public string? Notes { get; set; }
}
